name: Trigger auto deployment for alpaca-keeper

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/alpaca-keeper-AutoDeployTrigger-0eacbbae-bec2-4d7e-8de1-3adb5d6e4b72.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.ALPACAKEEPER_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.ALPACAKEEPER_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.ALPACAKEEPER_AZURE_SUBSCRIPTION_ID }}

      - name: Docker login to ACR
        run: echo "${{ secrets.ACR_PASSWORD }}" | docker login avsandboxacr.azurecr.io -u "${{ secrets.ACR_USERNAME }}" --password-stdin

      - name: Build image
        run: docker build -t avsandboxacr.azurecr.io/alpaca-keeper:${{ github.sha }} .

      - name: Push image
        run: docker push avsandboxacr.azurecr.io/alpaca-keeper:${{ github.sha }}

      - name: Update Container App image
        run: |
          az containerapp update \
            -g AVSandboxRessources \
            -n alpaca-keeper \
            --image avsandboxacr.azurecr.io/alpaca-keeper:${{ github.sha }}


